spring:
  datasource:
    url: jdbc:h2:~/test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  sql:
    init:
      mode: always
      encoding: UTF-8

  task:
    scheduling:
      pool:
        size: 10

  mail:
    host: smtp.gmail.com
    port: 587
    username: woomoon1107@gmail.com
    password: tglf mvgq spmx lwiv
    properties:
      mail.smtp.auth: true
      mail.smtp.timeout: 5000
      mail.smtp.starttls.enable: true

  h2:
    console:
      enabled: true
  redis:
    host: localhost
    port: 6379

jwt:
  header: Authorization
  secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff
  token-validity-in-seconds: 86400

iamport:
  api_key: 8114051028354368
  api_secret: EBUlx9b3D8SXaTQjJqeMi6f4AiKdxOIw0fAaYI9VTSvSBsxpKg95tFKajbRd919mKImxX9Rzxsfi9h9f
  api_url: https://api.iamport.kr

logging:
  level:
    org.springframework: info
    org.springframework.web: info